#ifndef MAP_EDITOR_CONSTANTS_H
#define MAP_EDITOR_CONSTANTS_H

#define TILE_WIDTH  16
#define TILE_HEIGHT 16

#define TILESET_PALETTE_TILES_ACROSS 4
#define TILESET_PALETTE_TILES_HIGH   8

/* TODO: adjust based on screen */
#define MAP_BORDER_LEFT   28
#define MAP_BORDER_TOP    51
#define MAP_BORDER_WIDTH  (MAP_TILES_WIDE * TILE_WIDTH  * 2 + 2)
#define MAP_BORDER_HEIGHT (MAP_TILES_HIGH * TILE_HEIGHT * 2 + 2)

#define MAP_NAME_LEFT   (MAP_BORDER_LEFT  + 80)
#define MAP_NAME_TOP    18
#define MAP_NAME_WIDTH  (MAP_BORDER_WIDTH - 81)
#define MAP_NAME_HEIGHT 14

/* TODO: adjust based on titlebar height */
#define CURRENT_TILESET_LEFT   378
#define CURRENT_TILESET_TOP    36
#define CURRENT_TILESET_WIDTH  144
#define CURRENT_TILESET_HEIGHT 12

#define CHOOSE_TILESET_LEFT    CURRENT_TILESET_LEFT
#define CHOOSE_TILESET_TOP     CURRENT_TILESET_TOP + CURRENT_TILESET_HEIGHT
#define CHOOSE_TILESET_HEIGHT  12
#define CHOOSE_TILESET_WIDTH   CURRENT_TILESET_WIDTH

#define TILESET_SCROLL_HEIGHT  TILE_HEIGHT * TILESET_PALETTE_TILES_HIGH * 2 + 2
#define TILESET_SCROLL_WIDTH   CHOOSE_TILESET_WIDTH - (TILE_WIDTH * TILESET_PALETTE_TILES_ACROSS * 2)
#define TILESET_SCROLL_LEFT    CURRENT_TILESET_LEFT + TILE_WIDTH * TILESET_PALETTE_TILES_ACROSS * 2 + 1
#define TILESET_SCROLL_TOP     CHOOSE_TILESET_TOP + CHOOSE_TILESET_HEIGHT + 8

#define TILESET_BORDER_LEFT   CURRENT_TILESET_LEFT
#define TILESET_BORDER_TOP    (TILESET_SCROLL_TOP + 1)
#define TILESET_BORDER_WIDTH  (TILE_WIDTH * TILESET_PALETTE_TILES_ACROSS * 2 + 2)
#define TILESET_BORDER_HEIGHT TILESET_SCROLL_HEIGHT

#define SONG_NAME_LEFT   (MAP_BORDER_LEFT + 95)
#define SONG_NAME_TOP    (MAP_BORDER_TOP + MAP_BORDER_HEIGHT + 20)
#define SONG_NAME_WIDTH  (MAP_BORDER_WIDTH - 182)
#define SONG_NAME_HEIGHT 14

#define SONG_CHANGE_LEFT   (SONG_NAME_LEFT + SONG_NAME_WIDTH - 2)
#define SONG_CHANGE_TOP    SONG_NAME_TOP
#define SONG_CHANGE_WIDTH  76
#define SONG_CHANGE_HEIGHT 14

#define SONG_CLEAR_LEFT   (SONG_CHANGE_LEFT + SONG_CHANGE_WIDTH - 2)
#define SONG_CLEAR_TOP    SONG_CHANGE_TOP
#define SONG_CLEAR_WIDTH  14
#define SONG_CLEAR_HEIGHT 14

#define MAP_LEFT_LEFT   (MAP_BORDER_LEFT - 15)
#define MAP_LEFT_TOP    MAP_BORDER_TOP - 2
#define MAP_LEFT_WIDTH  14
#define MAP_LEFT_HEIGHT MAP_BORDER_HEIGHT + 2

#define MAP_RIGHT_LEFT   (MAP_BORDER_LEFT + MAP_BORDER_WIDTH - 1)
#define MAP_RIGHT_TOP    MAP_LEFT_TOP
#define MAP_RIGHT_WIDTH  MAP_LEFT_WIDTH
#define MAP_RIGHT_HEIGHT MAP_LEFT_HEIGHT

#define MAP_UP_LEFT   (MAP_BORDER_LEFT - 3)
#define MAP_UP_TOP    (MAP_BORDER_TOP - 15)
#define MAP_UP_WIDTH  (MAP_BORDER_WIDTH + 4)
#define MAP_UP_HEIGHT 14

#define MAP_DOWN_LEFT   MAP_UP_LEFT
#define MAP_DOWN_TOP    (MAP_BORDER_TOP + MAP_BORDER_HEIGHT - 1)
#define MAP_DOWN_WIDTH  MAP_UP_WIDTH
#define MAP_DOWN_HEIGHT MAP_UP_HEIGHT

#define ENTITIES_LEFT   (TILESET_BORDER_LEFT - 1)
#define ENTITIES_TOP    (TILESET_BORDER_TOP + TILESET_BORDER_HEIGHT + 10)
#define ENTITIES_WIDTH  (TILESET_BORDER_WIDTH + TILESET_SCROLL_WIDTH)
#define ENTITIES_HEIGHT 14

#endif
